services:
  web:
    image: accounting-for-dentists
    build: .
    ports:
      - "8080:8080"
    environment:
      - Authentication:Microsoft:ClientSecret={CLIENT_SECRET}
      - Authentication:Microsoft:ClientId={CLIENT_ID}
      - ConnectionStrings__AccountingForDentists={CONNECTION_STRING}