// <auto-generated />
using System;
using AccountingForDentists.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountingForDentists.Migrations
{
    [DbContext(typeof(AccountingContext))]
    [Migration("20250713045024_RemoveFKNBetweenExpensesAndSales")]
    partial class RemoveFKNBetweenExpensesAndSales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccountingForDentists.Models.BusinessEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TenantId", "UserId", "Name");

                    b.HasIndex("TenantId", "UserId");

                    b.ToTable("Businesses");
                });

            modelBuilder.Entity("AccountingForDentists.Models.ContractualAgreementsEntity", b =>
                {
                    b.Property<Guid>("ContractualAgreementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ExpensesEntityExpensesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("SalesEntitySalesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ContractualAgreementId");

                    b.HasIndex("ExpensesEntityExpensesId");

                    b.HasIndex("SalesEntitySalesId");

                    b.HasIndex("TenantId", "UserId");

                    b.ToTable("ContractIncome");
                });

            modelBuilder.Entity("AccountingForDentists.Models.ExpensesEntity", b =>
                {
                    b.Property<Guid>("ExpensesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GST")
                        .HasColumnType("decimal(9,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ExpensesId");

                    b.HasIndex("TenantId", "UserId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("AccountingForDentists.Models.SalesEntity", b =>
                {
                    b.Property<Guid>("SalesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GST")
                        .HasColumnType("decimal(9,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SalesId");

                    b.HasIndex("UserId", "TenantId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("AccountingForDentists.Models.ContractualAgreementsEntity", b =>
                {
                    b.HasOne("AccountingForDentists.Models.ExpensesEntity", "ExpensesEntity")
                        .WithMany()
                        .HasForeignKey("ExpensesEntityExpensesId");

                    b.HasOne("AccountingForDentists.Models.SalesEntity", "SalesEntity")
                        .WithMany()
                        .HasForeignKey("SalesEntitySalesId");

                    b.Navigation("ExpensesEntity");

                    b.Navigation("SalesEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
