// <auto-generated />
using System;
using AccountingForDentists.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountingForDentists.Migrations
{
    [DbContext(typeof(AccountingContext))]
    [Migration("20250712090706_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccountingForDentists.Models.BusinessEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TenantId", "UserId", "Name");

                    b.ToTable("Businesses");
                });

            modelBuilder.Entity("AccountingForDentists.Models.ExpensesEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExpensesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GST")
                        .HasColumnType("decimal(9,2)");

                    b.Property<Guid?>("SalesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SalesTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SalesUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TenantId", "UserId", "ExpensesId");

                    b.HasIndex("SalesTenantId", "SalesUserId", "SalesId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("AccountingForDentists.Models.SalesEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SalesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GST")
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("TenantId", "UserId", "SalesId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("AccountingForDentists.Models.ServiceFacilitiesAgreementEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceFacilityAgreementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ExpensesEntityExpensesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExpensesEntityTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExpensesEntityUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("SalesEntitySalesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SalesEntityTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SalesEntityUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TenantId", "UserId", "ServiceFacilityAgreementId");

                    b.HasIndex("ExpensesEntityTenantId", "ExpensesEntityUserId", "ExpensesEntityExpensesId");

                    b.HasIndex("SalesEntityTenantId", "SalesEntityUserId", "SalesEntitySalesId");

                    b.ToTable("ServiceFacilitiesAgreements");
                });

            modelBuilder.Entity("AccountingForDentists.Models.ExpensesEntity", b =>
                {
                    b.HasOne("AccountingForDentists.Models.SalesEntity", "Sales")
                        .WithMany()
                        .HasForeignKey("SalesTenantId", "SalesUserId", "SalesId");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("AccountingForDentists.Models.ServiceFacilitiesAgreementEntity", b =>
                {
                    b.HasOne("AccountingForDentists.Models.ExpensesEntity", "ExpensesEntity")
                        .WithMany()
                        .HasForeignKey("ExpensesEntityTenantId", "ExpensesEntityUserId", "ExpensesEntityExpensesId");

                    b.HasOne("AccountingForDentists.Models.SalesEntity", "SalesEntity")
                        .WithMany()
                        .HasForeignKey("SalesEntityTenantId", "SalesEntityUserId", "SalesEntitySalesId");

                    b.Navigation("ExpensesEntity");

                    b.Navigation("SalesEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
