// <auto-generated />
using System;
using AccountingForDentists.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountingForDentists.Migrations
{
    [DbContext(typeof(AccountingContext))]
    partial class AccountingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("AccountingForDentists.Models.AttachmentEntity", b =>
                {
                    b.Property<Guid>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerFilename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MD5Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("AttachmentId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("AccountingForDentists.Models.BusinessEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Businesses");
                });

            modelBuilder.Entity("AccountingForDentists.Models.ContractIncomeEntity", b =>
                {
                    b.Property<Guid>("ContractualAgreementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExpensesEntityExpensesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvoiceDateReferenceDateContainerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SalesEntitySalesId")
                        .HasColumnType("TEXT");

                    b.HasKey("ContractualAgreementId");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("ExpensesEntityExpensesId");

                    b.HasIndex("InvoiceDateReferenceDateContainerId");

                    b.HasIndex("SalesEntitySalesId");

                    b.ToTable("ContractIncome");
                });

            modelBuilder.Entity("AccountingForDentists.Models.DateContainerEntity", b =>
                {
                    b.Property<Guid>("DateContainerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("DateContainerId");

                    b.ToTable("DateReferences");
                });

            modelBuilder.Entity("AccountingForDentists.Models.ExpensesEntity", b =>
                {
                    b.Property<Guid>("ExpensesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(9,2)");

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DateReferenceDateContainerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GST")
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("ExpensesId");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("DateReferenceDateContainerId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("AccountingForDentists.Models.SalesEntity", b =>
                {
                    b.Property<Guid>("SalesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(9,2)");

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DateReferenceDateContainerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GST")
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("SalesId");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("DateReferenceDateContainerId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("AccountingForDentists.Models.ContractIncomeEntity", b =>
                {
                    b.HasOne("AccountingForDentists.Models.AttachmentEntity", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId");

                    b.HasOne("AccountingForDentists.Models.ExpensesEntity", "ExpensesEntity")
                        .WithMany()
                        .HasForeignKey("ExpensesEntityExpensesId");

                    b.HasOne("AccountingForDentists.Models.DateContainerEntity", "InvoiceDateReference")
                        .WithMany()
                        .HasForeignKey("InvoiceDateReferenceDateContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccountingForDentists.Models.SalesEntity", "SalesEntity")
                        .WithMany()
                        .HasForeignKey("SalesEntitySalesId");

                    b.Navigation("Attachment");

                    b.Navigation("ExpensesEntity");

                    b.Navigation("InvoiceDateReference");

                    b.Navigation("SalesEntity");
                });

            modelBuilder.Entity("AccountingForDentists.Models.ExpensesEntity", b =>
                {
                    b.HasOne("AccountingForDentists.Models.AttachmentEntity", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId");

                    b.HasOne("AccountingForDentists.Models.DateContainerEntity", "DateReference")
                        .WithMany()
                        .HasForeignKey("DateReferenceDateContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("DateReference");
                });

            modelBuilder.Entity("AccountingForDentists.Models.SalesEntity", b =>
                {
                    b.HasOne("AccountingForDentists.Models.AttachmentEntity", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId");

                    b.HasOne("AccountingForDentists.Models.DateContainerEntity", "DateReference")
                        .WithMany()
                        .HasForeignKey("DateReferenceDateContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("DateReference");
                });
#pragma warning restore 612, 618
        }
    }
}
